create table
  public.constants (
    id bigint generated by default as identity not null,
    name character varying not null,
    value character varying not null,
    created_at timestamp with time zone null default now(),
    constraint constants_pkey primary key (id),
    constraint constants_name_key unique (name)
  ) tablespace pg_default;